name: "Pull Request Labeler"
on:
- pull_request_target

# this is an unnecessary comment
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
